version: '3.8'

services:
  app: &app
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile.app
      args:
        RUBY_VERSION: '2.6.5'
        PG_MAJOR: '12'
        NODE_MAJOR: '12'
        YARN_VERSION: '1.22.4'
        BUNDLER_VERSION: '2.1.4'
    image: example-dev:1.0.0
    tmpfs:
      - /tmp
  
  backend: &backend
    <<: *app
    stdin_open: true
    tty: true
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
    environment:
      - NODE_ENV=development
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/
      - APP_DATABASE_HOST=postgres
      - APP_DATABASE_USERNAME=postgres
      - APP_DATABASE_PASSWORD=<3c0dinG
      - BOOTSNAP_CACHE_DIR=/usr/local/bundle/_bootsnap
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - WEB_CONCURRENCY=1
      - HISTFILE=/app/log/.bash_history
      - PSQL_HISTFILE=/app/log/.psql_history
      - EDITOR=vim
    depends_on:
      - postgres
      - redis
    command: >
      bash -c "wait-for-it postgres:5432; wait-for-it redis:6379"

  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    ports:
      - '3000:3000'

  runner:
    <<: *backend
    command: /bin/bash

  postgres:
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile.postgres
    image: postgres-th:1.0.0
    volumes:
      # - .psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
      # - ./log:/root/log:cached
    environment:
      - POSTGRES_PASSWORD=<3c0dinG
      # - PSQL_HISTFILE=/root/log/.psql_history
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  redis:
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - RAILS_ENV=${RAILS_ENV:-development}
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0


volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs: